name:                hs
license:             WTFPL

dependencies:
- base >= 4.7 && < 5
- combinat
- text
- containers
- megaparsec
- parser-combinators
- unordered-containers
- split
- data-memocombinators
- lens
- mtl
- dlist
- unliftio-core
- stm
- transformers
- array
- ansi-terminal

library:
  source-dirs: src

tests:
  hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs
