name:                hs
license:             WTFPL

dependencies:
- base >= 4.7 && < 5
- combinat
- megaparsec
- text
- parser-combinators
- unordered-containers

library:
  source-dirs: src

tests:
  hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs
