name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  clojure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        env:
          cache-name: kaocha
        with:
          path: |
            ~/.gitlibs
            ~/.m2
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-
            ${{ runner.os }}-
      - uses: DeLaGuardo/setup-clojure@3.0
        with:
          cli: "1.10.1.739"
      - run: bin/kaocha
        working-directory: clj
